---
ID: "c7d5e6f7-a8b9-4c0d-1e2f-3a4b5c6d7e8f"
Parent: "a9c3d4e5-f6a7-4b8c-0d1e-2f3a4b5c6d7e"
Template: "a9c3d4e5-f6a7-4b8c-0d1e-2f3a4b5c6d7e"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/AHA Hero Banner/AHA Hero Banner Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F8B2C3D4-E5F6-4A7B-9C0D-1E2F3A4B5C6D}
    {A9C3D4E5-F6A7-4B8C-0D1E-2F3A4B5C6D7E}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "00000000-0000-0000-0000-00000000001b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260127T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00000000-0000-0000-0000-00000000001c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260127T120000Z
