---
ID: "92b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d"
Parent: "91a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"
Template: "91a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/In This Section/Rendering Parameters/In This Section Parameters/__Standard Values"
SharedFields:
- ID: "4be2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"
  Hint: HideTitle
  Value: 0
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "00000000-0000-0000-0000-000000000057"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260127T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00000000-0000-0000-0000-000000000058"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260127T120000Z
